// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11


#include "ui.h"
#include <Arduino.h>

void btnONevt(lv_event_t * e)
{
	digitalWrite(26,HIGH);
}

void btnOFFevt(lv_event_t * e)
{
	digitalWrite(26,LOW);
}
