// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: CPT_Test

#ifndef _CPT_TEST_UI_H
#define _CPT_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_moon_png);    // assets/moon.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
