// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: cydKeyboard

#ifndef _CYDKEYBOARD_UI_H
#define _CYDKEYBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include <stdio.h>

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Panel2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;
void ui_event_Keyboard1(lv_event_t * e);








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
