// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: DHT22

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -5);
    lv_obj_set_y(ui_Label6, -95);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "DHT22 DATA DISPLAY");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -4);
    lv_obj_set_y(ui_Label7, -49);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "TEMPERTURE");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF00D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -8);
    lv_obj_set_y(ui_Label8, 43);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "HUMIDITY");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0x0B9EFB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humiIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_humiIcon, &ui_img_humidity_png);
    lv_obj_set_width(ui_humiIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_humiIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_humiIcon, -79);
    lv_obj_set_y(ui_humiIcon, 84);
    lv_obj_set_align(ui_humiIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_humiIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_humiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempIcon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_tempIcon, &ui_img_temperature_png);
    lv_obj_set_width(ui_tempIcon, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_tempIcon, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_tempIcon, -84);
    lv_obj_set_y(ui_tempIcon, -3);
    lv_obj_set_align(ui_tempIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tempIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempVal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_tempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempVal, -4);
    lv_obj_set_y(ui_tempVal, -10);
    lv_obj_set_align(ui_tempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempVal, "30*C");
    lv_obj_set_style_text_color(ui_tempVal, lv_color_hex(0xFF0098), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempVal, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humiVal = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_humiVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humiVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humiVal, -4);
    lv_obj_set_y(ui_humiVal, 85);
    lv_obj_set_align(ui_humiVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humiVal, "60%");
    lv_obj_set_style_text_color(ui_humiVal, lv_color_hex(0x3A1AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humiVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humiVal, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


}
