// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: animation

#ifndef _ANIMATION_UI_H
#define _ANIMATION_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void arisu_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_arisu;
extern lv_obj_t * ui_Bar1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_arisu_arisu1_png);    // assets/arisu/arisu1.png
LV_IMG_DECLARE(ui_img_arisu_arisu2_png);    // assets/arisu/arisu2.png
LV_IMG_DECLARE(ui_img_arisu_arisu3_png);    // assets/arisu/arisu3.png
LV_IMG_DECLARE(ui_img_arisu_arisu4_png);    // assets/arisu/arisu4.png
LV_IMG_DECLARE(ui_img_arisu_arisu5_png);    // assets/arisu/arisu5.png
LV_IMG_DECLARE(ui_img_arisu_arisu6_png);    // assets/arisu/arisu6.png
LV_IMG_DECLARE(ui_img_arisu_arisu7_png);    // assets/arisu/arisu7.png
LV_IMG_DECLARE(ui_img_arisu_arisu8_png);    // assets/arisu/arisu8.png
LV_IMG_DECLARE(ui_img_arisu_arisu9_png);    // assets/arisu/arisu9.png
LV_IMG_DECLARE(ui_img_arisu_arisu10_png);    // assets/arisu/arisu10.png
LV_IMG_DECLARE(ui_img_arisu_arisu11_png);    // assets/arisu/arisu11.png
LV_IMG_DECLARE(ui_img_arisu_arisu12_png);    // assets/arisu/arisu12.png
LV_IMG_DECLARE(ui_img_arisu_arisu13_png);    // assets/arisu/arisu13.png
LV_IMG_DECLARE(ui_img_arisu_arisu14_png);    // assets/arisu/arisu14.png
LV_IMG_DECLARE(ui_img_arisu_arisu15_png);    // assets/arisu/arisu15.png
LV_IMG_DECLARE(ui_img_arisu_arisu16_png);    // assets/arisu/arisu16.png
LV_IMG_DECLARE(ui_img_arisu_arisu17_png);    // assets/arisu/arisu17.png
LV_IMG_DECLARE(ui_img_arisu_arisu18_png);    // assets/arisu/arisu18.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
