// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: switch

#include "ui.h"
#include "ui_helpers.h"

#define NUM_SWITCHES  3 //Number switch you want to use
bool switch_states[NUM_SWITCHES] = {false}; //Set the initial state of the switch to false.

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_event_Switch1(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[0] = lv_obj_has_state(target, LV_STATE_CHECKED);

        // If SW0 is on, turn on all.
        if (switch_states[0]) {
            switch_states[1] = true;
            switch_states[2] = true;
            _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_state_modify(ui_Switch3, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &ui_img_lighton_png);
            _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_lighton_png);
        } 
        // If SW0 is off, turn off all (but can still be turned on individually).
        else {
            switch_states[1] = false;
            switch_states[2] = false;
            _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_state_modify(ui_Switch3, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, &ui_img_lightoff_png);
            _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, & ui_img_lightoff_png);
        }
        _ui_checked_set_text_value(ui_Label1, target, "ALL ON", "ALL OFF");

    }

}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[1] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image1, _UI_IMAGE_PROPERTY_IMAGE, switch_states[1] ? &ui_img_lighton_png : &ui_img_lightoff_png);
       
         //Check if both SW1 & SW2 are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
        //When SW1 OFF, then SW0 is off
        if (!switch_states[1]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
    }

}
void ui_event_Switch3(lv_event_t * e){
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[2] = lv_obj_has_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image2, _UI_IMAGE_PROPERTY_IMAGE, switch_states[2] ? &ui_img_lighton_png : &ui_img_lightoff_png);

         // Check if both SW1 & SW2 are on, then SW0 will turn on automatically.
        if (switch_states[1] && switch_states[2]) {
            switch_states[0] = true;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        } else if (!switch_states[1] && !switch_states[2]) {
            switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }   
        //When SW2 OFF, then SW0 is off
        if (!switch_states[2]){
             switch_states[0] = false;
            _ui_state_modify(ui_Switch1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
            _ui_checked_set_text_value(ui_Label1, target, "ALL ON","ALL OFF");
        }
 }

}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
