// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: switch

#ifndef _SWITCH_UI_H
#define _SWITCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

#define NUM_SWITCHES  3
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui____initial_actions0;

//extern bool get_switch_state(int sw_index);
extern bool switch_states[NUM_SWITCHES];  
//extern int sw_index;





LV_IMG_DECLARE(ui_img_lighton_png);    // assets/lightON.png
LV_IMG_DECLARE(ui_img_lightoff_png);    // assets/lightOff.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
