// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: gauge

#ifndef _GAUGE_UI_H
#define _GAUGE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_gauge;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_index;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_gauge_png);    // assets/gauge.png
LV_IMG_DECLARE(ui_img_blurspeed_png);    // assets/blurspeed.png
LV_IMG_DECLARE(ui_img_index_png);    // assets/index.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
