// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: gauge

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gauge = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_gauge, &ui_img_gauge_png);
    lv_obj_set_width(ui_gauge, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gauge, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_gauge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_gauge, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_gauge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 223);
    lv_obj_set_height(ui_Arc1, 223);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 93);
    lv_arc_set_bg_angles(ui_Arc1, 90, 0);
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x15FF5B), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 40, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_Arc1, &ui_img_blurspeed_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_index = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_index, &ui_img_index_png);
    lv_obj_set_width(ui_index, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_index, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_index, 0);
    lv_obj_set_y(ui_index, 72);
    lv_obj_set_align(ui_index, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_index, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_index, 5, -28);
    lv_image_set_rotation(ui_index, 2500);

}
