// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: cydKeyboard

#ifndef _CYDKEYBOARD_UI_H
#define _CYDKEYBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Panel2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;

extern char wifi_ssid[32];
extern char wifi_password[32];

const char * get_wifi_ssid();
const char * get_wifi_password();

void ui_event_KeyBoard1(lv_event_t * e);

LV_IMG_DECLARE(ui_img_wifierr_png);    // assets/wifierr.png
LV_IMG_DECLARE(ui_img_wifiok_png);    // assets/wifiok.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
