// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: CYD SWitch

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

#define NUM_SWITCHES  6 //Number switch you want to use
bool switch_states[NUM_SWITCHES] = {false}; //Set the initial state of the switch to false.
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Panel2;
void ui_event_Switch2(lv_event_t * e);
lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
void ui_event_Switch4(lv_event_t * e);
lv_obj_t * ui_Switch4;
void ui_event_Switch5(lv_event_t * e);
lv_obj_t * ui_Switch5;
lv_obj_t * ui_Switch6;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui____initial_actions0;


///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
         /** Check if the target object has the LV_STATE_CHECKED state
		 and store the result in the switch_states array at position 0 **/
        switch_states[0] = lv_switch_get_state(target, LV_STATE_CHECKED);
        /** Check if the switch_states array at position 0 is true or false
         and set the image property of the ui_image object accordingly **/
        _ui_image_set_property(ui_Image1,_UI_IMAGE_PROPERTY_IMAGE, switch_states[0] ? & ui_img_onlight_png : & ui_img_offlight_png);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
       switch_states[1] = lv_switch_get_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image2,_UI_IMAGE_PROPERTY_IMAGE, switch_states[1] ? & ui_img_onlight_png : & ui_img_offlight_png);

    }
}
void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
       switch_states[2] = lv_switch_get_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image3,_UI_IMAGE_PROPERTY_IMAGE, switch_states[2] ? & ui_img_onlight_png : & ui_img_offlight_png);
    }
}

void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[3] = lv_switch_get_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image4,_UI_IMAGE_PROPERTY_IMAGE, switch_states[3] ? & ui_img_onlight_png : & ui_img_offlight_png);
    }
}
void ui_event_Switch5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_states[4] = lv_switch_get_state(target, LV_STATE_CHECKED);
        _ui_image_set_property(ui_Image5,_UI_IMAGE_PROPERTY_IMAGE, switch_states[4] ? & ui_img_onlight_png : & ui_img_offlight_png);
    }
}
///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
